# -*- coding: utf-8 -*-
"""10k_episodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6RbB0Lo-g4irctkgLZiP-j3GWBgg_6-
"""

!pip install trl

!pip install accelerate
!pip install datasets
!pip install rich
!pip install transformers>=4.46.0

!pip install git+https://github.com/huggingface/transformers.git

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

from google.colab import drive
drive.mount('/content/drive')

!python ppo_tldr.py \
    --dataset_name trl-internal-testing/tldr-preference-sft-trl-style \
    --dataset_test_split validation \
    --learning_rate 3e-6 \
    --output_dir /content/drive/MyDrive/Jun_23_output \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --total_episodes 10000 \
    --model_name_or_path EleutherAI/pythia-1b-deduped \
    --sft_model_path cleanrl/EleutherAI_pythia-1b-deduped__sft__tldr \
    --reward_model_path cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr \
    --missing_eos_penalty 1.0 \
    --stop_token eos \
    --response_length 52 \
    --eval_strategy steps \
    --eval_steps 100 \
    --use_peft True

